fix:修复Firefox和Safari浏览器获取不到AudioContext、录音失败问题
paraself/mp3-recorder pull request #1
Opened 2019-09-26 03:36 UTC by Lelouch-cc

2019-09-26 05:35 UTC, paraself requested changes

2019-09-26 05:35 UTC, paraself commented on src/index.ts
> +window.AudioContext = window.AudioContext || window.webkitAudioContext
这个有必要么？下面的constructor里，不是做了检测吗？

2019-09-26 05:35 UTC, paraself commented on src/index.ts
> +        .getUserMedia({ audio: true })
FF和Safari主要是因为这个所以可以用了么？那看来deviceId是不需要的，那从IConfig开始，就可以整个把deviceId移除了吧？

2019-09-26 06:05 UTC, Lelouch-cc commented on src/index.ts
> +window.AudioContext = window.AudioContext || window.webkitAudioContext
> 这个有必要么？下面的constructor里，不是做了检测吗？

FF和Safari里面会报错

2019-09-26 06:33 UTC, Lelouch-cc commented on src/index.ts
> +window.AudioContext = window.AudioContext || window.webkitAudioContext
有，Safari浏览器会报错

[Vue warn]: Error in v-on handler (Promise/async): "ReferenceError: Can't find variable: AudioContext"

2019-09-26 06:37 UTC, Lelouch-cc commented on src/index.ts
> +        .getUserMedia({ audio: true })
deviceId已经移除

2019-09-27 02:20 UTC, paraself commented on src/index.ts
> +window.AudioContext = window.AudioContext || window.webkitAudioContext
重写了context实例化部分

2019-09-27 02:20 UTC, merged

2019-09-27 02:22 UTC, paraself commented
已发布 4.8.2